CREATE TABLE cfae_contacts (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  name VARCHAR2(200) NOT NULL,
  email VARCHAR2(320) NOT NULL,
  message CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT cfae_contacts_pk PRIMARY KEY (id)
);
